services:
  softwer.dev-client:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8070:80"
    depends_on:
      - softwer.dev-server

  softwer.dev-server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
